### ISSUE TITLE
About likelihood

### ISSUE THREAD

**Issue by qjr1997** [aalto-intelligent-robotics/sivl#1]
Hi，I want to ask that if I don't know whether the images matched true or false ，how can I calculate the likelihood？

**Comment by jkinnari** [comment]
Hi! In [the manuscript](https://arxiv.org/pdf/2110.01967.pdf), the likelihood is calculate using equation 3.

With the code in this repository, you can do this by calling the function getLookup in [learnLikelihood.py](https://github.com/aalto-intelligent-robotics/sivl/blob/main/code/learnLikelihood.py). getLookup then returns `ys_learning` and `probs_learning`. `ys_learning` is a range of values for c and `probs_learning` is the likelihood. You can then use these as a lookup table of likelihoods corresponding with values of c, from which you can interpolate the likelihood for any value of c.

Maybe this could have been clarified in more detail in the code and I must admit using `y` in the code and `c` in the manuscript may be confusing.

Hope this helps in seeing the correspondence of the manuscript and the code and feel free to ask for more details.

**Comment by qjr1997** [comment]
Sorry , I'm still confused about  " assume the priorsfor values of S are p(o) = β,p(s) = p(u) = (1 −β)/2 " mentioned in the paper.
I can't understand why assume  " p(s) = p(u) " . In a practical situation  , I guess the p(s) will gradually bigger than p(u) with MCL iteration and equation 3 would  invalid. I mean the 1k particles are random, nobody knows they matched true or false. So how to get the likelihood in that case?

**Comment by jkinnari** [comment]
We are following the MCL implementation in citation [3] (S. Thrun, W. Burgard, and D. Fox, Probabilistic Robotics (Intelligent Robotics and Autonomous Agents). The MIT Press, 2005.). See Table 8.2 in section 8.3.2 in [3]. We do resampling at each time step. Weight for resampling is determined by equation 3 in the manuscript, without prior knowledge on p(s) or p(u).
