### ISSUE TITLE
Inquiry about the Implementation of Monte-Carlo Localization 

### ISSUE THREAD

**Issue by wangerniuniu** [aalto-intelligent-robotics/sivl#3]
Hello,
I recently came across your open-source code repository and was impressed by the depth and quality of your work. The effort you have put into sharing your research findings and making them accessible to the community is truly commendable. It has provided researchers like me with valuable resources to learn from and build upon.

Recently, I attempted to find the specific implementation details of the Monte-Carlo localization part in your open-source code, but I couldn't locate the relevant information. Therefore, I decided to reach out to you in the hopes of obtaining guidance regarding its implementation.

**Comment by jkinnari** [comment]
Hello, thank you for showing interest towards this piece of work and for your kind words. The Monte-Carlo localization implementation of this paper is not published in this repository, but it's very similar to what is described in [Thrun et al's Probabilistic Robotics](https://mitpress.mit.edu/9780262201629/probabilistic-robotics/) chapter 4.2. See algorithm Particle_filter for the particle filter part and Low_variance_sampler for resampling. I hope this helps!
